services:
  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe-network
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe-network
    volumes:
      - redis-cache-data:/data

  redis-socketio:
    image: redis:6.2-alpine
    networks:
      - frappe-network
    volumes:
      - redis-cache-data:/data

volumes:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
