x-erpnext-backend-image: &erpnext_backend_image
  image: marty/erpnext-worker:${ERPNEXT_VERSION:?No ERPNext version set}
  deploy:
    placement:
      constraints: [node.hostname == ns3064432]
    restart_policy:
      condition: on-failure
  networks:
    - frappe-network

services:

  backend:
    <<: *erpnext_backend_image
    deploy:
      replicas: 3

  frontend:
    image: marty/erpnext-nginx:${ERPNEXT_VERSION}
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik_traefik-net"
        - "traefik.frontend.rule=Host:test.mh-receptions.com, erpnext.mh-receptions.com"
        - "traefik.frontend.entryPoints=https,http"
    networks:
      - frappe-network
      - traefik_traefik-net

  queue-short:
    <<: *erpnext_backend_image
    deploy:
      replicas: 3

  queue-default:
    <<: *erpnext_backend_image
    deploy:
      replicas: 4

  queue-long:
    <<: *erpnext_backend_image
    deploy:
      replicas: 2

  scheduler:
    <<: *erpnext_backend_image
