
x-backend-defaults: &backend_defaults
  image: frappe/frappe-worker:${FRAPPE_VERSION:?No Frappe version set}
  volumes:
    - sites:/home/frappe/frappe-bench/sites
    - assets:/home/frappe/frappe-bench/sites/assets:ro
  environment:
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    REDIS_CACHE: ${REDIS_CACHE}
    REDIS_QUEUE: ${REDIS_QUEUE}
    REDIS_SOCKETIO: ${REDIS_SOCKETIO}
    SOCKETIO_PORT: 9000

services:

  backend:
    <<: *backend_defaults

  frontend:
    image: frappe/frappe-nginx:${FRAPPE_VERSION}
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$$host}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
    networks:
      - frappe-network
    volumes:
      - sites:/usr/share/nginx/html/sites
      - assets:/usr/share/nginx/html/assets

  websocket:
    image: frappe/frappe-socketio:${FRAPPE_VERSION}
    networks:
      - frappe-network
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  queue-short:
    <<: *backend_defaults
    command: bench worker --queue short

  queue-default:
    <<: *backend_defaults
    command: bench worker --queue default

  queue-long:
    <<: *backend_defaults
    command: bench worker --queue long

  scheduler:
    <<: *backend_defaults
    command: bench schedule

# ERPNext requires local assets access (Frappe does not)
volumes:
  assets:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/debian/frappe_docker/sites/assets
  sites:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/debian/frappe_docker/sites

networks:
  traefik_traefik-net:
    external: true
  frappe-network:
    external: true
